int _putchar(char c);
void _puts_recursion(char *s);
int factorial(int n);
void _print_rev_recursion(char *s);
int _pow_recursion(int x, int y);
int _strlen_recursion(char *s);
int pow_opt(int x, int y);
int _sqrt_recursion(int n);
int divide_available(int num, int div);
int is_prime_number(int n);
