void _puts_recursion(char *s);
int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int square_find(int x, int y);
int _sqrt_recursion(int n);
int div_available(int num, int div);
int is_prime_number(int n);
int wildcmp(char *s1, char *s2)i;
int _strlen(char *str);
int compar(char *str, int num1, int num2);
int is_palindrome(char *s);
